# Generated by Django 5.2.17 on 2026-09-20 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('medical', 'Servicios Médicos'), ('school', 'Colegios y Educación'), ('transportation', 'Transporte'), ('shopping', 'Centros Comerciales y Tiendas')], max_length=50),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='chatbot.house')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
