# Generated by Django 5.2.17 on 2026-09-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_place_category_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='codigo',
            field=models.CharField(default='SIN-CODIGO', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='house',
            name='dormitorios',
            field=models.IntegerField(default=1),
        ),
    ]
