# Generated by Django 5.2.17 on 2026-09-28 01:19

from django.db import migrations, models


def limpiar_precios(apps, schema_editor):
    """Convierte '$480,000' en '480000' para que pase a Decimal."""
    House = apps.get_model('chatbot', 'House')
    for casa in House.objects.all():
        limpio = str(casa.price).replace("$", "").replace(",", "").strip()
        if limpio != str(casa.price):
            casa.price = limpio
            casa.save(update_fields=['price'])


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_house_codigo_house_dormitorios'),
    ]

    operations = [
        migrations.RunPython(limpiar_precios, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
